
[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "Maple Mono SC NF"
style = "Regular"

[scrolling]
history = 10000

[general]
import = [
    "~/.config/alacritty/themes/themes/doom_one.toml"
]

[terminal]

[terminal.shell]
program = "/usr/local/bin/fish"
